import { divisions, families, cards, sheets } from './card-canon.js';

const state={view:'codex',division:'all',family:'all',query:'',selected:cards[0],turn:1,resources:{command:6,insight:6,essence:6},lanes:[[],[],[]]};
const app=document.querySelector('#app');
const divMap=new Map(divisions.map(d=>[d.id,d]));
const familyMark={Specimen:'◉',Weapon:'⚔',Monster:'◆',Knight:'♜',Warrior:'▲',Magician:'✦',Environment:'⌁',Disaster:'⚠',Defense:'⬡',Base:'▣',Item:'◇',Operative:'◎',Action:'➤',Trap:'⌖',Reaction:'↶',Response:'↳',Law:'§',Spell:'✧',Hex:'⛧',Plague:'☣',Virus:'⌬',Dragon:'♢',Deity:'☀',Android:'◈',God:'✹',Ruler:'♛',Ritual:'⟲',World:'◌'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const artStyle=c=>`--art-x:${c.art.col};--art-y:${c.art.row};--division:${divMap.get(c.divisionId).color}`;
const icon=(d,large=false)=>`<span class="divisionIcon ${large?'large':''}" style="--division:${d.color}">${d.icon}</span>`;
const costs=c=>`<span class="cost command"><i>C</i>${c.cost.command}</span><span class="cost insight"><i>I</i>${c.cost.insight}</span><span class="cost essence"><i>E</i>${c.cost.essence}</span>`;

function card(c,compact=false){const d=divMap.get(c.divisionId);return `<button class="codexCard ${compact?'compact':''} ${state.selected?.id===c.id?'selected':''}" data-card="${c.id}" style="${artStyle(c)}"><div class="frameCorner tl"></div><div class="frameCorner tr"></div><header class="cardHead"><span class="familyMark">${familyMark[c.family]||'✦'}</span><div><small>${esc(d.name)} · ${esc(c.family)}</small><strong>${esc(c.name)}</strong></div><b class="power">${c.power}</b></header><div class="cardArt" role="img" aria-label="Artwork for ${esc(c.name)}"></div><div class="cardMeta"><span>${esc(c.rarity)}</span><span>${esc(c.setLabel)}</span></div><section class="rules"><div class="ruleTop"><b>${esc(c.family)}</b><span>${costs(c)}</span></div>${compact?'':`<p>${esc(c.rulesText)}</p><div class="tags">${c.keywords.slice(0,3).map(k=>`<span>${esc(k)}</span>`).join('')}</div>`}</section><footer><span>${esc(c.id)}</span><span>${esc(c.timing)} · ${esc(c.targeting)}</span></footer></button>`}

function shell(body){return `<header class="topbar"><button class="brand" data-view="overview"><b>✦</b><span><strong>THE COLLECTIVE CODEX</strong><small>TWENTY-ONE DIVISIONS · INFINITE OUTCOMES</small></span></button><nav>${['overview','codex','battlefield'].map(v=>`<button data-view="${v}" class="${state.view===v?'active':''}">${v}</button>`).join('')}</nav><div class="online">● 1,134 CARD CANON ONLINE</div></header>${body}<footer class="siteFooter"><span>COLLECTIVE AI INC · ARCHITECTING A HUMANE FUTURE</span><span>CANON BUILD 1.0 · EMBEDDED ART ATLAS</span></footer>`}

function overview(){return shell(`<main class="overview"><section class="hero"><div class="heroCopy"><span class="eyeline">LIVING DIGITAL CARD GAME</span><h1>1,134 cards.<br>Every one alive.</h1><p>All fifty-four selection sheets are mapped into a single canonical card system: division identity, family treatment, rules text, resource economy and embedded artwork stay synchronized from Codex browser to battlefield.</p><div class="actions"><button class="primary" data-view="codex">Browse the full Codex</button><button data-view="battlefield">Enter battlefield</button></div></div><div class="heroFan">${cards.filter((_,i)=>i%54===0).slice(0,7).map((c,i)=>`<div style="--fan:${i-3}">${card(c,true)}</div>`).join('')}</div></section><section class="metrics"><article><strong>1,134</strong><span>Canonical cards</span></article><article><strong>54</strong><span>Embedded art sheets</span></article><article><strong>28</strong><span>Card families</span></article><article><strong>21</strong><span>Division identities</span></article></section><section class="divisionSection"><div class="sectionTitle"><span>LOCKED DIVISION SYSTEM</span><h2>Twenty-one doctrines, one Codex.</h2></div><div class="divisionGrid">${divisions.map(d=>`<button data-division="${d.id}" style="--division:${d.color}"><header><span>${String(d.id).padStart(2,'0')}</span>${icon(d,true)}</header><strong>${d.name}</strong><p>${d.doctrine}</p><footer>${d.keywords.map(k=>`<span>${k}</span>`).join('')}</footer></button>`).join('')}</div></section></main>`)}

function codex(){const q=state.query.trim().toLowerCase();const filtered=cards.filter(c=>(state.division==='all'||c.divisionId===Number(state.division))&&(state.family==='all'||c.family===state.family)&&(!q||`${c.name} ${c.family} ${divMap.get(c.divisionId).name} ${c.rulesText} ${c.id}`.toLowerCase().includes(q)));return shell(`<main class="codex"><aside class="divisionRail"><button data-division="all" class="${state.division==='all'?'active':''}"><span class="divisionIcon">∞</span><span>ALL DIVISIONS</span></button>${divisions.map(d=>`<button data-division="${d.id}" class="${String(state.division)===String(d.id)?'active':''}" style="--division:${d.color}">${icon(d)}<span><small>${String(d.id).padStart(2,'0')}</small>${d.name}</span></button>`).join('')}</aside><section class="codexMain"><header class="toolbar"><div><span>CANONICAL CARD REGISTRY</span><h1>${filtered.length.toLocaleString()} cards visible</h1><p>Each card maps to one embedded atlas tile and one finalized rules record.</p></div><div class="toolbarControls"><label>SEARCH<input id="search" value="${esc(state.query)}" placeholder="Name, rule, ID or division"></label><label>FAMILY<select id="family"><option value="all">All card families</option>${families.map(f=>`<option ${state.family===f?'selected':''}>${f}</option>`).join('')}</select></label></div></header><div class="summary"><span>${sheets.length} source sheets</span><span>1,134 art coordinates</span><span>1500×2100 export masters</span><span>Hybrid division × family frames</span></div><div class="cards">${filtered.map(c=>card(c)).join('')}</div></section></main>`)}

function battlefield(){const hand=[cards[0],cards[89],cards[367],cards[801],cards[1050]];return shell(`<main class="battlePage"><header class="battleHeading"><div><span>LOCAL RULES SIMULATION</span><h1>Living three-lane battlefield</h1></div><button id="reset">Reset match</button></header><section class="battle"><div class="status"><span>YOUR CORE <b>20</b></span><span>TURN <b>${state.turn}</b></span><span>RIVAL CORE <b>20</b></span></div><div class="resources">${costs({cost:state.resources})}</div><div class="lanes">${['Vanguard','Conduit','Flank'].map((name,i)=>`<article><header><b>${name}</b><button data-deploy="${i}">Deploy selected</button></header><div class="enemy">RIVAL FIELD · AWAITING DOCTRINE</div><div class="center">CONTESTED ZONE</div><div class="player">${state.lanes[i].map(c=>`<div class="unit" style="${artStyle(c)}"><div class="unitArt"></div><b>${esc(c.name)}</b><small>PWR ${c.power}</small></div>`).join('')}</div></article>`).join('')}</div><div class="hand"><header><div><span>DOCTRINE HAND</span><b>${esc(state.selected?.name||'Select a card')}</b></div><button class="primary" id="endTurn">End turn</button></header><div>${hand.map(c=>card(c,true)).join('')}</div></div></section></main>`)}

function render(){app.innerHTML=state.view==='overview'?overview():state.view==='codex'?codex():battlefield();bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>{state.view=el.dataset.view;render()});document.querySelectorAll('[data-division]').forEach(el=>el.onclick=()=>{state.division=el.dataset.division==='all'?'all':Number(el.dataset.division);state.view='codex';render()});document.querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{state.selected=cards.find(c=>c.id===el.dataset.card);if(state.view!=='battlefield')render()});const search=document.querySelector('#search');if(search)search.oninput=e=>{state.query=e.target.value;render()};const fam=document.querySelector('#family');if(fam)fam.onchange=e=>{state.family=e.target.value;render()};document.querySelectorAll('[data-deploy]').forEach(el=>el.onclick=()=>{const c=state.selected,i=Number(el.dataset.deploy),r=state.resources;if(!c||state.lanes[i].length>=3||r.command<c.cost.command||r.insight<c.cost.insight||r.essence<c.cost.essence)return;r.command-=c.cost.command;r.insight-=c.cost.insight;r.essence-=c.cost.essence;state.lanes[i].push(c);render()});document.querySelector('#endTurn')?.addEventListener('click',()=>{state.turn++;state.resources={command:Math.min(10,5+Math.floor(state.turn/2)),insight:Math.min(10,5+Math.floor(state.turn/3)),essence:Math.min(10,4+Math.floor(state.turn/4))};render()});document.querySelector('#reset')?.addEventListener('click',()=>{state.turn=1;state.resources={command:6,insight:6,essence:6};state.lanes=[[],[],[]];render()})}
render();
export {state};
