const divisions = [
  [1,'Collective AI','✦','#D4A843','Command synthesis and adaptive doctrine',['Synthesize','Observe','Converge']],
  [2,'ZenFlow','❖','#7C3AED','Prediction, sequencing and neural links',['Forecast','Link','Reorder']],
  [3,'The Collective','✦','#067A56','Recruitment, economy and compound value',['Recruit','Prosper','Compound']],
  [4,'Hybrid Living','✎','#0EA5E9','Learning, adaptation and transformation',['Learn','Adapt','Graduate']],
  [5,'Nexus Labs','❝','#DC2626','Narrative control, replay and authored outcomes',['Record','Replay','Edit']],
  [6,'Kinetic Edge','⚔','#16A34A','Momentum, movement and repeated attacks',['Dash','Combo','Impact']],
  [7,'Quantum Ledger','◈','#8B5CF6','Deferred value, exchange and resource control',['Invest','Settle','Yield']],
  [8,'Juris Guard','⚖','#C9A84C','Judgment, restrictions and punishment',['Judge','Statute','Sentence']],
  [9,'Signal Velocity','▲','#F43F5E','Broadcast amplification and cascading effects',['Broadcast','Amplify','Cascade']],
  [10,'Cognara Mind','✶','#E0267E','Psychic control and intent manipulation',['Probe','Confuse','Dominate']],
  [11,'Terra Axis','⛏','#8C2B2B','Structures, armor and battlefield permanence',['Fortify','Anchor','Construct']],
  [12,'Binary Loom','▦','#A3E635','Modular synthesis and card construction',['Compile','Weave','Assemble']],
  [13,'Vector Shift','➤','#CBD5E1','Logistics, routing and repositioning',['Route','Transfer','Shift']],
  [14,'Aether Link','⚯','#B5451B','Portals, summoning and cross-lane support',['Portal','Relay','Bridge']],
  [15,'Obsidian Arc','◫','#E2E8F0','Security, lockdown and counterattacks',['Lock','Breach','Retaliate']],
  [16,'Civic Core','❀','#F7CFCF','Cooperation, healing and shared benefit',['Shelter','Unite','Restore']],
  [17,'Nomad Nexus','☉','#D4A574','Reserve play, travel and temporary camps',['Roam','Reserve','Caravan']],
  [18,'Vital Helix','⚕','#14B8A6','Regeneration, mutation and medicine',['Heal','Mutate','Regrow']],
  [19,'Gaia Synthesis','☘','#2F7D4B','Ecosystems, living terrain and swarms',['Seed','Bloom','Symbiosis']],
  [20,'Eon Core','⌛','#FFFBEB','Time manipulation, delay and recursion',['Delay','Rewind','Preserve']],
  [21,'Animus Prime','◇','#22D3EE','Androids, automation and autonomous actions',['Deploy','Automate','Drone']]
].map(([id,name,icon,color,doctrine,keywords])=>({id,name,icon,color,doctrine,keywords}));

const families = ['Specimen','Weapon','Monster','Knight','Warrior','Magician','Environment','Disaster','Defense','Base','Item','Operative','Action','Trap','Reaction','Response','Law','Spell','Hex','Plague','Virus','Dragon','Deity','Android','God','Ruler','Ritual','World'];
const sheetCounts = {Specimen:1,Weapon:12,Monster:1,Knight:1,Warrior:1,Magician:1,Environment:2,Disaster:1,Defense:1,Base:1,Item:8,Operative:8,Action:1,Trap:1,Reaction:1,Response:1,Law:1,Spell:1,Hex:1,Plague:1,Virus:1,Dragon:1,Deity:1,Android:1,God:1,Ruler:1,Ritual:1,World:1};
const nouns = {Specimen:['Chimera','Warden','Crawler','Mote'],Weapon:['Halberd','Lance','Glaive','Cannon'],Monster:['Devourer','Colossus','Horror','Maw'],Knight:['Sentinel','Templar','Custodian','Paladin'],Warrior:['Vanguard','Striker','Marauder','Champion'],Magician:['Oracle','Arcanist','Weaver','Seer'],Environment:['Sanctum','Frontier','Nexus','Reach'],Disaster:['Fracture','Collapse','Storm','Rupture'],Defense:['Bulwark','Ward','Aegis','Bastion'],Base:['Citadel','Foundry','Haven','Spire'],Item:['Relic','Module','Cache','Talisman'],Operative:['Marshal','Agent','Captain','Specialist'],Action:['Advance','Strike','Surge','Protocol'],Trap:['Snare','Mine','Web','Lock'],Reaction:['Counter','Deflect','Riposte','Override'],Response:['Reply','Recovery','Acknowledgement','Fallback'],Law:['Mandate','Statute','Edict','Decree'],Spell:['Invocation','Convergence','Lance','Ward'],Hex:['Omen','Curse','Knot','Seal'],Plague:['Blight','Fever','Rot','Swarm'],Virus:['Strain','Vector','Worm','Splice'],Dragon:['Wyrm','Drake','Serpent','Leviathan'],Deity:['Ascendant','Avatar','Celestial','Eidolon'],Android:['Frame','Unit','Automaton','Construct'],God:['Sovereign','Titan','Creator','Overseer'],Ruler:['Regent','Archon','Imperator','Chancellor'],Ritual:['Rite','Communion','Consecration','Accord'],World:['Prime','Dominion','Expanse','Sphere']};
const sheets=[]; for(const family of families) for(let i=1;i<=sheetCounts[family];i++) sheets.push({id:`${family.toLowerCase()}-${i}`,family,set:i});
const cards=sheets.flatMap((sheet,sheetIndex)=>divisions.map(d=>({id:`${sheet.id}-${d.id}`,division:d,family:sheet.family,set:sheet.set,name:`${d.name==='Collective AI'?'Aureate':d.name.split(' ')[0]} ${nouns[sheet.family][(sheetIndex+d.id)%4]} ${String(sheetIndex+1).padStart(2,'0')}`,rarity:['Common','Uncommon','Rare','Epic','Legendary'][(sheetIndex+d.id)%5],power:2+((sheetIndex+d.id)%9),command:(sheetIndex+d.id)%4,insight:(sheetIndex+d.id+1)%4,essence:(sheetIndex+d.id+2)%4,provisional:true})));

const state={view:'overview',division:'all',family:'all',query:'',selected:cards.find(c=>c.family==='Operative'),turn:1,resources:{command:3,insight:2,essence:1},lanes:[[],[],[]]};
const app=typeof document==='undefined'?null:document.querySelector('#app');
const icon=d=>`<span class="icon" style="--division:${d.color}">${d.icon}</span>`;
function card(c,compact=false){return `<button class="card ${state.selected?.id===c.id?'selected':''} ${compact?'compact':''}" data-card="${c.id}" style="--division:${c.division.color}"><header><span>${c.command+c.insight+c.essence}</span>${icon(c.division)}</header><div class="art"><b>${c.division.icon}</b><small>${c.family}</small></div><section><strong>${c.name}</strong><em>${c.family} Set ${c.set}</em>${compact?'':`<p>${c.division.keywords[(c.power+c.set)%3]} — resolve an effect aligned with ${c.division.doctrine.toLowerCase()}.</p>`}</section><footer><span>${c.rarity}</span><span>PWR ${c.power}</span></footer></button>`}
function shell(content){return `<header class="topbar"><button class="brand" data-view="overview"><b>✦</b><span><strong>THE COLLECTIVE CODEX</strong><small>TWENTY-ONE DIVISIONS · INFINITE OUTCOMES</small></span></button><nav>${['overview','codex','battlefield'].map(v=>`<button data-view="${v}" class="${state.view===v?'active':''}">${v}</button>`).join('')}</nav><div class="online">● REGISTRY ONLINE</div></header>${content}<footer class="footer"><span>COLLECTIVE AI INC · ARCHITECTING A HUMANE FUTURE</span><span>BUILD 0.1 · VERCEL TARGET</span></footer>`}
function overview(){return shell(`<main class="overview"><section class="hero"><div><span class="eyeline">LIVING DIGITAL CARD GAME</span><h1>Every card changes the battlefield.</h1><p>Build across twenty-one doctrines, command animated units, rewrite laws, channel rituals and confront an intelligence that learns how you play.</p><div class="actions"><button class="primary" data-view="battlefield">Enter battlefield</button><button data-view="codex">Open the Codex</button></div></div><div class="constellation"><div class="core">✦</div>${divisions.slice(1).map((d,i)=>{const a=i/20*Math.PI*2,r=i%2?31:42;return `<span style="left:${50+Math.cos(a)*r}%;top:${50+Math.sin(a)*r}%;color:${d.color}">${d.icon}</span>`}).join('')}</div></section><section class="metrics"><article><strong>21</strong><span>Playable divisions</span></article><article><strong>54</strong><span>Developed sheets</span></article><article><strong>1,134</strong><span>Registry entries</span></article><article><strong>28</strong><span>Card families</span></article></section><section class="divisionSection"><h2>The twenty-one doctrines</h2><div class="divisionGrid">${divisions.map(d=>`<button data-division="${d.id}" style="--division:${d.color}"><header><span>${String(d.id).padStart(2,'0')}</span><b>${d.icon}</b></header><strong>${d.name}</strong><p>${d.doctrine}</p><footer>${d.keywords.map(k=>`<span>${k}</span>`).join('')}</footer></button>`).join('')}</div></section></main>`)}
function codex(){const q=state.query.toLowerCase();const filtered=cards.filter(c=>(state.division==='all'||c.division.id===Number(state.division))&&(state.family==='all'||c.family===state.family)&&(!q||`${c.name} ${c.family} ${c.division.name}`.toLowerCase().includes(q)));return shell(`<main class="codex"><aside><button data-division="all">∞ All divisions</button>${divisions.map(d=>`<button data-division="${d.id}" class="${String(state.division)===String(d.id)?'active':''}">${icon(d)}<span>${String(d.id).padStart(2,'0')} ${d.name}</span></button>`).join('')}</aside><section><header class="toolbar"><div><span>CANONICAL REGISTRY</span><h1>${filtered.length.toLocaleString()} entries visible</h1></div><div><input id="search" value="${state.query}" placeholder="Search cards, families or divisions"><select id="family"><option value="all">All card families</option>${families.map(f=>`<option ${state.family===f?'selected':''}>${f}</option>`).join('')}</select></div></header><div class="summary"><span>${sheets.length} sheets indexed</span><span>${divisions.length} locked icons</span><span>Registry schema v0.1</span></div><div class="cards">${filtered.slice(0,126).map(c=>card(c)).join('')}</div></section></main>`)}
function battlefield(){const hand=[cards.find(c=>c.division.id===1&&c.family==='Operative'),cards.find(c=>c.division.id===2&&c.family==='Spell'),cards.find(c=>c.division.id===11&&c.family==='Defense'),cards.find(c=>c.division.id===21&&c.family==='Android'),cards.find(c=>c.division.id===19&&c.family==='Monster')];return shell(`<main class="battlePage"><header><div><span>VERTICAL SLICE · LOCAL SIMULATION</span><h1>Three-lane living battlefield</h1></div><button id="reset">Reset match</button></header><section class="battle"><div class="status"><span>YOUR CORE <b>20</b></span><span>TURN <b>${state.turn}</b></span><span>RIVAL CORE <b>20</b></span></div><div class="resources">Command ${state.resources.command} · Insight ${state.resources.insight} · Essence ${state.resources.essence}</div><div class="lanes">${['Vanguard','Conduit','Flank'].map((name,i)=>`<article><header><b>${name}</b><button data-deploy="${i}" ${state.selected?'':'disabled'}>Deploy selected</button></header><div class="enemy">Rival field awaiting doctrine</div><div class="center">CONTESTED ZONE</div><div class="player">${state.lanes[i].map(c=>`<div class="unit" style="--division:${c.division.color}"><b>${c.division.icon}</b><span>${c.name}</span><small>${c.power+3} integrity</small></div>`).join('')}</div></article>`).join('')}</div><div class="hand"><header><div><span>DOCTRINE HAND</span><b>${state.selected?.name||'Select a card'}</b></div><button class="primary" id="endTurn">End turn</button></header><div>${hand.map(c=>card(c,true)).join('')}</div></div></section></main>`)}
function render(){if(!app)return;app.innerHTML=state.view==='overview'?overview():state.view==='codex'?codex():battlefield();bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>{state.view=el.dataset.view;render()});document.querySelectorAll('[data-division]').forEach(el=>el.onclick=()=>{state.division=el.dataset.division==='all'?'all':Number(el.dataset.division);state.view='codex';render()});document.querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{state.selected=cards.find(c=>c.id===el.dataset.card);render()});const search=document.querySelector('#search');if(search)search.oninput=e=>{state.query=e.target.value;render()};const family=document.querySelector('#family');if(family)family.onchange=e=>{state.family=e.target.value;render()};document.querySelectorAll('[data-deploy]').forEach(el=>el.onclick=()=>{const i=Number(el.dataset.deploy),c=state.selected;if(!c||state.lanes[i].length>=3)return;if(state.resources.command<c.command||state.resources.insight<c.insight||state.resources.essence<c.essence)return;state.resources.command-=c.command;state.resources.insight-=c.insight;state.resources.essence-=c.essence;state.lanes[i].push(c);render()});document.querySelector('#endTurn')?.addEventListener('click',()=>{state.turn++;state.resources={command:Math.min(10,3+Math.floor(state.turn/2)),insight:Math.min(10,2+Math.floor(state.turn/3)),essence:Math.min(10,1+Math.floor(state.turn/4))};render()});document.querySelector('#reset')?.addEventListener('click',()=>{state.turn=1;state.resources={command:3,insight:2,essence:1};state.lanes=[[],[],[]];render()})}
render();
export { divisions, families, sheets, cards };
