import './materialize-atlas.mjs';
import { cp, mkdir, rm, readFile, writeFile } from 'node:fs/promises';

const out = 'dist';

/* The CSS sources live in src/css/ as small, readable, layered files and are
 * concatenated here into the three stylesheets index.html already requests.
 * index.html is not owned by the design layer, so the number and the names of
 * the stylesheets are fixed; the cascade below is the design decision:
 *
 *   styles.css  foundation — fonts, tokens, reset, shell, controls, the card
 *   match.css   the board — the one screen that re-densifies the card
 *   ui.css      screens, motion, responsive and the a11y fallbacks that must
 *               win over everything above them
 *
 * Order is an explicit list, never a directory read, so the output is
 * byte-for-byte deterministic.
 */
const cssBundles = {
  'styles.css': [
    '00-fonts.css', '01-tokens.css', '02-divisions.css', '03-reset.css',
    '04-shell.css', '05-controls.css', '06-notify.css', '07-card.css',
  ],
  'match.css': [
    '20-match-board.css', '21-match-units.css', '22-match-hand.css',
  ],
  'ui.css': [
    '30-codex.css', '31-deck.css', '32-static.css',
    '33-motion.css', '34-responsive.css', '35-a11y.css',
  ],
};

/* Block comments are stripped from the built file — the sources carry ~1,000
 * lines of rationale and shipping it costs 12.3 KB gzipped, which is a sixth of
 * the whole transfer budget. Line structure and indentation are preserved, so
 * the artifact is still readable; the reasoning lives in src/css/. This is safe
 * for this codebase because no string or url() in it contains the sequence that
 * opens a comment, and CSS block comments cannot nest. */
const stripComments = css => css
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/[ \t]+$/gm, '')
  .replace(/\n{3,}/g, '\n\n')
  .trim();

async function bundleCss() {
  for (const [target, parts] of Object.entries(cssBundles)) {
    const chunks = [`/* GENERATED by scripts/build.mjs — do not edit; edit src/css/ and rebuild.\n   Sources, in cascade order: ${parts.map(p => `src/css/${p}`).join(', ')}\n   Rationale, tokens and measured contrast tables: docs/design-system.md */\n`];
    for (const part of parts) {
      chunks.push(`\n/* ${part} */\n`);
      chunks.push(stripComments(await readFile(`src/css/${part}`, 'utf8')));
      chunks.push('\n');
    }
    await writeFile(target, chunks.join(''));
  }
}

const rootFiles = ['index.html', 'styles.css', 'match.css', 'ui.css', 'app.js', 'card-canon.js', 'match-engine.js', 'deck-store.js'];
const srcFiles = ['core.js', 'cards.js', 'ui.js', 'terms.js', 'glossary.js', 'vgrid.js', 'motion.js', 'screen-codex.js', 'screen-deck.js', 'screen-match.js', 'screen-static.js', 'prematch.js'];
const fontFiles = ['space-grotesk-latin-var.woff2', 'jetbrains-mono-latin-var.woff2'];

await bundleCss();
await rm(out, { recursive: true, force: true });
await mkdir(`${out}/assets/fonts`, { recursive: true });
await mkdir(`${out}/src`, { recursive: true });
for (const f of rootFiles) await cp(f, `${out}/${f}`);
for (const f of srcFiles) await cp(`src/${f}`, `${out}/src/${f}`);
for (const f of fontFiles) await cp(`assets/fonts/${f}`, `${out}/assets/fonts/${f}`);
await cp('assets/card-art-atlas.avif', `${out}/assets/card-art-atlas.avif`);
await cp('assets/card-art-provenance.json', `${out}/assets/card-art-provenance.json`);
console.log(`Built static Collective Codex to dist/ (${rootFiles.length + srcFiles.length} files + ${fontFiles.length} fonts + assets)`);
