import './materialize-atlas.mjs';
import { cp, mkdir, rm } from 'node:fs/promises';
const out='dist';
const rootFiles=['index.html','styles.css','match.css','ui.css','app.js','card-canon.js','match-engine.js','deck-store.js'];
const srcFiles=['core.js','cards.js','ui.js','terms.js','glossary.js','vgrid.js','motion.js','screen-codex.js','screen-deck.js','screen-match.js','screen-static.js','prematch.js'];
await rm(out,{recursive:true,force:true});
await mkdir(`${out}/assets`,{recursive:true});
await mkdir(`${out}/src`,{recursive:true});
for(const f of rootFiles) await cp(f,`${out}/${f}`);
for(const f of srcFiles) await cp(`src/${f}`,`${out}/src/${f}`);
await cp('assets/card-art-atlas.avif',`${out}/assets/card-art-atlas.avif`);
await cp('assets/card-art-provenance.json',`${out}/assets/card-art-provenance.json`);
console.log(`Built static Collective Codex to dist/ (${rootFiles.length+srcFiles.length} files + assets)`);
